### ISSUE TITLE
Readme example optional parts of the URL doesn't work

### ISSUE THREAD

**Issue by fridays** [alubbe/named-routes#10]
The example from the readme:

Full support for optional parts of the URL
```
app.get('/admin/(user/(edit/:id/)(album/:albumId/):session/)test', 'admin', function(req, res, next){
    console.log(req.params);
});
```
Gives the following error:
```
SyntaxError: Invalid regular expression: /^\/admin\/(?(?:([^\/]+?))\/(?(?:([^\/]+?))\/(?:([^\/]+?))\/)(album\/(?:([^\/]+?))\/)(?:([^\/]+?))\/)test\/?$/: Invalid group
```

**Comment by alubbe** [comment]
Yes, the readme was unclear about this - I've just updated it.
When you use named-routes in the `express` mode, the paths that you enter have to be compatible with the syntax of `express`: https://github.com/alubbe/named-routes#as-a-replacement-for-express-framework-router
This will give you simple optional parts.

If you want the full power of nested optional parts, you will need to use the standalone version and use
```js
router.add('get', '/admin/(user/(edit/:id/)(album/:albumId/):session/)test', 'admin', function(req, res, next){
    console.log(req.params);
});
```
You can even use this inside of express, simply call `router.dispatch(req)` in a middleware instead of `router.extendExpress(app)`.

**Comment by alubbe** [comment]
@fridays did that answer your question? I'd like to close the issue.

**Comment by fridays** [comment]
@alubbe Thank you, I'll consider using the standalone version
