### ISSUE TITLE
Add support for absolute URL generation

### ISSUE THREAD

**Issue by slavafomin** [alubbe/named-routes#27]
Hello!

Thank you for this great library!

However, I would really love to see support for absolute URL generation. Sometimes you will need to generate an absolute URL for a specific route to use it in e.g. E-Mail message, the relative URL will just not work.

For example, [Symfony 2 has such an option](http://symfony.com/doc/current/routing.html#generating-absolute-urls) in it's Router component and it works great, very convenient. I would suggest to implement the same functionality.

We could use it like this:

``` js
let articleUrl = router.build('article', {
  slug: article.slug
}, { // <-- "build" function's API is extended with optional config object
  absolute: true
});
```

The effective base URL [could be obtained from the request](http://stackoverflow.com/a/10185427/1056679), i.e.:

``` js
var baseUrl = req.protocol + '://' + req.get('host');
```

**Comment by slavafomin** [comment]
Here's my naive middleware implementation to demonstrate the idea:

```js
app.use(function (req, res, next) {
  req.getRouteUrl = function (routeName, params, options) {
    let url = app.namedRoutes.build(routeName, params);
    if (options && options.absolute) {
      let baseUrl = req.protocol + '://' + req.get('host');
      url = baseUrl + url;
    }
    return url;
  };
  next();
});
```

It adds `getRouteUrl()` function to the `req` object.

Here's how I use it:

```js
res.render('main/lesson', {
  addthis_url: req.getRouteUrl('index', {
    slug: lesson.slug
  }, { absolute: true })
});
```

**Comment by alubbe** [comment]
Hey @slavafomin thanks for taking the time.
Unfortunately, this does not work with the re-usability of our routers, see https://github.com/alubbe/named-routes#extending-express4-routers
In short, the `articleUrl` might not only be missing the protocol and host, but also part of the path leading up to it. The router does not know whether it is mounted to the root path or somewhere deeper. This must be implemented by the consumer of this package because only there do you have the full information of how the absolute paths are constructed.
